### PR TITLE
Add hamming error, cleanup buffering, fix settings crash

### LINKED ISSUE #10: Settings menu crashes sometimes
It's not always reproducible, so perhaps it has something to do with thread-safety in between the new threads.

```
I/DetectionThread: Interrupted while waiting for camera frame: null
I/AprilTag: Finished pause.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: edu.umich.eecs.april.apriltag, PID: 26622
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.access$600(Camera.java:152)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1219)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### LINKED ISSUE #12: Add minimum error parameter

### PR DESCRIPTION
**Pull request by messenger-sean**

### CODE REVIEW

File: src/main/java/edu/umich/eecs/april/apriltag/ApriltagDetectorActivity.java [hunk 1]
```diff
@@ -128,11 +128,12 @@ protected void onResume() {
         double decimation = Double.parseDouble(sharedPreferences.getString("decimation_list", "8"));
         double sigma = Double.parseDouble(sharedPreferences.getString("sigma_value", "0"));
         int nthreads = Integer.parseInt(sharedPreferences.getString("nthreads_value", "4"));
+        int max_hamming_error = Integer.parseInt(sharedPreferences.getString("max_hamming_error", "0"));
```
Comment (johnjwang) [inline src/main/java/edu/umich/eecs/april/apriltag/ApriltagDetectorActivity.java:131]: Good catch, that must've been causing the FPs. Although IIRC the default at April was something > 0 for robustness to noise(?)

**Review by johnjwang — APPROVED** [review]

File: src/main/java/edu/umich/eecs/april/apriltag/ApriltagDetectorActivity.java (hunk 1 above)
Comment (messenger-sean) [reply src/main/java/edu/umich/eecs/april/apriltag/ApriltagDetectorActivity.java:131]: the default hardcoded value when we init the apriltag detector was 2 here. probably was based on 36h11, where 2 error bits is still totally likely to be a tag -- but for 16h5, that's just _so_ noisy.

Comment (johnjwang) [reply src/main/java/edu/umich/eecs/april/apriltag/ApriltagDetectorActivity.java:131]: Oh yes, it's obvious now that I try it. So many false detections from noise
